#!/bin/sh
#item   ####description                                      ###on off ###
rm -f /tmp/SeTnewtag # empty the return file
dialog --title "SELECTING PACKAGES FROM SERIES A (BASE LINUX SYSTEM)" \
       --checklist "Please select the packages you wish to install \
from series A. Use the \
UP/DOWN keys to scroll through the list, and the SPACE key to select \
the packages you wish to install. Certain important packages have \
already been selected for you, and you are cautioned against unselecting \
these packages. However, it's your system. :^)  For instance, be sure to \
install LILO or you won't be able to make system bootdisks. \
Press ENTER when you are \
done." 21 72 8 \
"aaa_base" "Basic filesystem, shell, and utils - REQUIRED" "on" \
"bash" "GNU bash-1.14.6 shell - REQUIRED" "on" \
"han"  "Hangul on Linux Console - RECOMMENDED" "on" \
"devs" "Device files found in /dev - REQUIRED" "on" \
"etc"  "System config files & utilities - REQUIRED" "on" \
"ide"  "Linux 2.0.0 no SCSI (YOU NEED 1 KERNEL)" "on" \
"scsi" "Linux 2.0.0 with SCSI (YOU NEED 1 KERNEL)" "on" \
"modules" "Modular Linux device drivers" "on" \
"hdsetup" "Slackware setup scripts - REQUIRED" "on" \
"lilo" "Boots Linux (not UMSDOS), DOS, OS/2, etc." "on" \
"loadlin" "Boots Linux (UMSDOS too!) from MS-DOS" "on" \
"umsprogs" "Utilities needed to use the UMSDOS filesystem" "on" \
"sysvinit" "System V-like INIT programs - REQUIRED" "on" \
"bin"      "GNU fileutils 3.12, elvis, etc. - REQUIRED" "on" \
"ldso" "Dynamic linker/loader - REQUIRED" "on" \
"ibcs2" "Runs SCO/SysVr4 binaries" "off" \
"less" "A text pager utility - REQUIRED" "on" \
"pcmcia" "PCMCIA card services support" "off" \
"getty" "Getty_ps 2.0.7e - OPTIONAL" "off" \
"gzip"  "The GNU zip compression - REQUIRED" "on" \
"ps" "Displays process info - REQUIRED" "on" \
"aoutlibs" "a.out shared libs - RECOMMENDED" "on" \
"elflibs" "The ELF shared C libraries - REQUIRED" "on" \
"util" "Util-linux utilities - REQUIRED" "on" \
"comms" "Serial transfer and modem comm packages" "on" \
"cpio" "The GNU cpio backup/archiving utility" "on" \
"e2fsbn" "Utilities for the ext2 file system" "on" \
"find" "GNU findutils 4.1" "on" \
"grep" "GNU grep 2.0" "on" \
"keytbls" "Change keyboard mappings" "on" \
"gpm" "Cut and paste text with your mouse" "on" \
"sh_utils" "GNU sh-utils 1.12 - REQUIRED" "on" \
"sysklogd" "Logs system and kernel messages" "on" \
"tar" "GNU tar 1.11.8 - REQUIRED" "on" \
"tcsh" "Extended C shell version 6.06" "off" \
"ksh" "PD-ksh 5.2.3, Korn Shell" "off" \
"txtutils" "GNU textutils-1.13 - REQUIRED" "on" \
"zoneinfo" "Configures your time zone" "on" \
2> /tmp/SeTpkgs
if [ $? = 1 -o $? = 255 ]; then
 rm -f /tmp/SeTpkgs
 exit
fi
cat /dev/null > /tmp/SeTnewtag
for PACKAGE in aaa_base devs etc ide scsi lilo sysvinit bin ldso \
bash getty gzip ps aoutlibs elflibs util comms cpio e2fsbn find grep keytbls \
less gpm sh_utils hdsetup sysklogd tar tcsh txtutils zoneinfo \
modules ibcs2 umsprogs loadlin pcmcia han ksh ; do
 if fgrep \"$PACKAGE\" /tmp/SeTpkgs 1> /dev/null 2> /dev/null ; then
  echo "$PACKAGE: ADD" >> /tmp/SeTnewtag
 else
  echo "$PACKAGE: SKP" >> /tmp/SeTnewtag
 fi
done
rm -f /tmp/SeTpkgs
